# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import radio_mcp_pb2 as radio__mcp__pb2

GRPC_GENERATED_VERSION = '1.83.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in radio_mcp_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class RadioMcpServiceStub:
    """Generic bridge over every MCP tool registered in server.py.
    Arguments and results travel as JSON strings so the contract stays stable
    no matter how tools are added or re-shaped (schemas are self-describing
    via ListTools).
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CallTool = channel.unary_unary(
                '/radiomcp.RadioMcpService/CallTool',
                request_serializer=radio__mcp__pb2.CallToolRequest.SerializeToString,
                response_deserializer=radio__mcp__pb2.CallToolResponse.FromString,
                _registered_method=True)
        self.ListTools = channel.unary_unary(
                '/radiomcp.RadioMcpService/ListTools',
                request_serializer=radio__mcp__pb2.ListToolsRequest.SerializeToString,
                response_deserializer=radio__mcp__pb2.ListToolsResponse.FromString,
                _registered_method=True)


class RadioMcpServiceServicer:
    """Generic bridge over every MCP tool registered in server.py.
    Arguments and results travel as JSON strings so the contract stays stable
    no matter how tools are added or re-shaped (schemas are self-describing
    via ListTools).
    """

    def CallTool(self, request, context):
        """Call any tool by name; `arguments_json` is the JSON object of tool args.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListTools(self, request, context):
        """Enumerate tools with their JSON schemas (name, description, input_schema).
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_RadioMcpServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CallTool': grpc.unary_unary_rpc_method_handler(
                    servicer.CallTool,
                    request_deserializer=radio__mcp__pb2.CallToolRequest.FromString,
                    response_serializer=radio__mcp__pb2.CallToolResponse.SerializeToString,
            ),
            'ListTools': grpc.unary_unary_rpc_method_handler(
                    servicer.ListTools,
                    request_deserializer=radio__mcp__pb2.ListToolsRequest.FromString,
                    response_serializer=radio__mcp__pb2.ListToolsResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'radiomcp.RadioMcpService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('radiomcp.RadioMcpService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class RadioMcpService:
    """Generic bridge over every MCP tool registered in server.py.
    Arguments and results travel as JSON strings so the contract stays stable
    no matter how tools are added or re-shaped (schemas are self-describing
    via ListTools).
    """

    @staticmethod
    def CallTool(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/radiomcp.RadioMcpService/CallTool',
            radio__mcp__pb2.CallToolRequest.SerializeToString,
            radio__mcp__pb2.CallToolResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListTools(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/radiomcp.RadioMcpService/ListTools',
            radio__mcp__pb2.ListToolsRequest.SerializeToString,
            radio__mcp__pb2.ListToolsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
